### ISSUE TITLE
State Column Missing on last build

### ISSUE THREAD

**Issue by charlesereed** [sdmlua/covid-19-drive-thru-sites#3]
The state column is not in the file from the most recent build. Will that be coming back?

**Comment by aaraney** [comment]
@charlesereed that's odd, it looks like 6bc85e0 resolved the issue. The script that scrapes the locations does not check for specific column headers, so that much have been an issue on the goodRX side of things.

**Comment by charlesereed** [comment]
Yup, confirmed, looks good now.  Thanks @aaraney.
